//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Calendar.Framework.Entity
{
    using System;
    using System.Collections.Generic;
    using Microsoft.EntityFrameworkCore;
    using System.Runtime.Serialization;
    
     [DataContract(IsReference = true)]
     [Serializable]
     public partial class AutoCodePart : EntityBase
     {
        public AutoCodePart()
        {
            this.AutoCodeCounter = new HashSet<AutoCodeCounter>();
        }
    
    
    	#region Copy
    	/// <summary>
        /// Clones or copy an object.
        /// </summary>
        /// <remarks>
        /// <para>The object to be cloned must be serializable.</para>
        /// <para>The serialization is to use the 
        /// <see cref="System.Xml.Serialization.XmlSerializer" />.
        /// </para>
        /// </remarks>
        /// <returns>AuditUser  object.</returns>
        public AutoCodePart Copy()
        {
            return (AutoCodePart)this.MemberwiseClone();
        }
        
        /// <summary>
        /// Creates the new copy of the entity.
        /// </summary>
        public AutoCodePart CreateObject()
        {
            return new AutoCodePart();
        }
    
        #endregion
    
    		[DataMember]
    		public string  AutoCodeID
    		{
    			 get
    			{
    				return lautocodeid;
    			}
    
    			 set
    			{
    				if (lautocodeid != value)
    				{
    					if (base.EntityState == EntityState.Modified)
    						base.RecordStateValue("AutoCodeID", new Tuple<object, object>(lautocodeid, value));
         				if(value != null)
        					lautocodeid = value.Trim();
        				else
        					lautocodeid = string.Empty;
    				}
    			}
    		}
    		private string lautocodeid = string.Empty;
    		
    		[DataMember]
    		public byte  PartOrder
    		{
    			 get
    			{
    				return lpartorder;
    			}
    
    			 set
    			{
    					if (lpartorder != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("PartOrder", new Tuple<object, object>(lpartorder, value));
    						lpartorder = value;
    					}
    			}
    		}
    		private byte lpartorder = default(byte);
    		
    		[DataMember]
    		public byte  PartType
    		{
    			 get
    			{
    				return lparttype;
    			}
    
    			 set
    			{
    					if (lparttype != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("PartType", new Tuple<object, object>(lparttype, value));
    						lparttype = value;
    					}
    			}
    		}
    		private byte lparttype = default(byte);
    		
    		[DataMember]
    		public byte  DynamicType
    		{
    			 get
    			{
    				return ldynamictype;
    			}
    
    			 set
    			{
    					if (ldynamictype != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("DynamicType", new Tuple<object, object>(ldynamictype, value));
    						ldynamictype = value;
    					}
    			}
    		}
    		private byte ldynamictype = default(byte);
    		
    		[DataMember]
    		public string  Value
    		{
    			 get
    			{
    				return lvalue;
    			}
    
    			 set
    			{
    				if (lvalue != value)
    				{
    					if (base.EntityState == EntityState.Modified)
    						base.RecordStateValue("Value", new Tuple<object, object>(lvalue, value));
         				if(value != null)
        					lvalue = value.Trim();
        				else
        					lvalue = string.Empty;
    				}
    			}
    		}
    		private string lvalue = string.Empty;
    		
    		[DataMember]
    		public int  CounterStartValue
    		{
    			 get
    			{
    				return lcounterstartvalue;
    			}
    
    			 set
    			{
    					if (lcounterstartvalue != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("CounterStartValue", new Tuple<object, object>(lcounterstartvalue, value));
    						lcounterstartvalue = value;
    					}
    			}
    		}
    		private int lcounterstartvalue = default(int);
    		
    		[DataMember]
    		public byte  CounterLength
    		{
    			 get
    			{
    				return lcounterlength;
    			}
    
    			 set
    			{
    					if (lcounterlength != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("CounterLength", new Tuple<object, object>(lcounterlength, value));
    						lcounterlength = value;
    					}
    			}
    		}
    		private byte lcounterlength = default(byte);
    		
    		[DataMember]
    		public byte  CounterResetBy
    		{
    			 get
    			{
    				return lcounterresetby;
    			}
    
    			 set
    			{
    					if (lcounterresetby != value)
    					{
    						if (base.EntityState == EntityState.Modified)
    							this.RecordStateValue("CounterResetBy", new Tuple<object, object>(lcounterresetby, value));
    						lcounterresetby = value;
    					}
    			}
    		}
    		private byte lcounterresetby = default(byte);
    		
    		[DataMember]
    		public string  AppId
    		{
    			 get
    			{
    				return lappid;
    			}
    
    			 set
    			{
    				if (lappid != value)
    				{
    					if (base.EntityState == EntityState.Modified)
    						base.RecordStateValue("AppId", new Tuple<object, object>(lappid, value));
    					lappid = value;
    				}
    			}
    		}
    		private string lappid;
    		
    		[DataMember]
    		public string  COLUMNC16
    		{
    			 get
    			{
    				return lcolumnc16;
    			}
    
    			 set
    			{
    				if (lcolumnc16 != value)
    				{
    					if (base.EntityState == EntityState.Modified)
    						base.RecordStateValue("COLUMNC16", new Tuple<object, object>(lcolumnc16, value));
    					lcolumnc16 = value;
    				}
    			}
    		}
    		private string lcolumnc16;
    		
    		[DataMember]
    		public string  COLUMNC17
    		{
    			 get
    			{
    				return lcolumnc17;
    			}
    
    			 set
    			{
    				if (lcolumnc17 != value)
    				{
    					if (base.EntityState == EntityState.Modified)
    						base.RecordStateValue("COLUMNC17", new Tuple<object, object>(lcolumnc17, value));
    					lcolumnc17 = value;
    				}
    			}
    		}
    		private string lcolumnc17;
    		
    
        [DataMember]
    public virtual AutoCode AutoCode { get; set; }
        [DataMember]
    public virtual ICollection<AutoCodeCounter> AutoCodeCounter { get; set; }
    }
}
